#SubmissionLinkRestService local configuration
#Active directory configuration
AD_DOMAIN: "fhlmc.com"
AD_URL: "ldaps://fhlmc.com"
AD_GROUP: "slsdactg"
AD_EXPIRATION_SECONDS: 600
AD_MAX_RETRY_ATTEMPTS: 2
AD_RETRY_DELAY_MS: 50
    
#Logging Levels
FW_LOG_LEVEL: "INFO"
APP_LOG_LEVEL: "DEBUG"

#Swagger UI
SW_ENABLE_FLAG: true

#Hikari slrs datasource configuration
SLS_DB_CLASSNAME: "com.ibm.db2.jcc.DB2Driver"
SLS_DB_URL: "jdbc:db2://he3qlxvddbs1126:50001/SLSDDB2"
SLS_DB_SCHEMA: "UDBADM"
SLS_DB_USER: "slsddbd1"
SLS_DB_SECRETS_LOCATION: "SLSDevDbWrite0219"

#Hikari slrs connection pool configuration   
SLS_DB_MAXIMUM_CP_SIZE: 15
SLS_DB_MINIMUM_CP_IDLE: 1

#MacVault alias for sls db
SLS_DB_MAC_VAULT_ALIAS: "BA0315-SLS-DEV_slsddbd3_AD_FHLMC"
SLS_DB_MAC_VAULT_TYPE: "Default"

#SRS configuration
SLS_MATCH_LOG_CACHE_FLAG: true
SLS_SUBMISSION_QUERY_FETCH_LIMIT: 1000
SLS_SUBMISSION_QUERY_FETCH_CEILING_LIMIT: 50000
SLS_BORROWER_QUERY_PARAMETER_IDPMLSUBMNLINK_SIZE_LIMIT: 5000
SLS_ENABLE_CONCURRENCY_FLAG: true
SLS_ENABLE_QUERY_LOGGING_FLAG: true
SLS_LOG_REQUEST_FLAG: true
SLS_LOG_RESPONSE_FLAG: true
SLS_EXCEPTION_RETRY_LIMIT: 3
SLS_EXCEPTION_RETRY_DELAY: 100
SLS_HINDSIGHT_MODE: "OFF"
SLS_HINDSIGHT_PROCESSING_CEILING_LIMIT: 100
SLS_MATCHES_PER_SUBMISSION_SIZE_LIMIT: 1000
SLS_APPRAISAL_IDENTIFIER_EXCLUDE_PATTERN: "1111111111"
SLS_LOAN_UNDERWRITING_CASE_IDENTIFIER_EXCLUDE_PATTERN: 
SLS_MERSMIN_IDENTIFIER_EXCLUDE_PATTERN: "112233445566778899"
SLS_LENDER_LOAN_IDENTIFIER_EXCLUDE_PATTERN: "^0+$,^1+$,^[a-zA-Z ]+$,^1234$,^12345$,^123456$,^1234567$,^12345678$,^123456789$,^[a-zA-Z0-9]{3}$,^[a-zA-Z0-9]{2}$,^[a-zA-Z0-9]{1}$"
SLS_ADDRESS_LINE_TEXT_MATCH_EXCLUDE_PATTERN: "0000 PREAPPROVAL ST,0000 PREAPPROVAL STREET,1 TBD,1 TO BE DETERMINED,123 MAIN ST,123 E MAIN ST,123 MAIN,123 MAIN STREET,123 N MAIN ST,123 PRE-APPROVAL,123 S MAIN ST,123 STREET,123 TBD,123 TBD ST,123 TBD STREET,123 UNKNOWN,123 W MAIN ST,1234 MAIN ST,1234 TBD,555 TBD,456 SOMEWHERE AVE,N PROPERTY,N PROPERTY ADDRESS,N/A,NO PROPERTY,NO PROPERTY ADDRESS,PRE APPROVAL,PREAPPROVAL,PRE-APPROVAL,PREQUAL,PRE-QUAL,PREQUAL ONLY,PREQUALIFICATION,SEE ATTACHED EXHIBIT A,TBA,TBD,TBD STREET,TBD TBD,TO BE DETERMINED,UNKNOWN"
SLS_STUBBED_PARTNER_ID_PATTERN: "000601"
SLS_SPLUNK_LOGGING_ENABLED_FLAG: true
SLS_SLA_1_SUBMISSION_THRESHOLD: 1000
SLS_SLA_5000_SUBMISSION_THRESHOLD: 900000
SLS_SLA_MAX_SUBMISSION_THRESHOLD: 900000

#SLMS configuration
#SITINT Environment
#SLMS_ENDPOINT="https://slms-main-sit1.sit.ocp.paasfhlmcnp.com/slms"
#SLMS_AUTH_USER="slstact1"
#SLMS_SECRETS_LOCATION="XXXXXX"
#DEV Environment
SLMS_ENDPOINT: "https://slms-main-dev1.dev.ocp.paasfhlmcnp.com/slms"
SLMS_AUTH_USER: "slsdact1"
SLMS_SECRETS_LOCATION: "SlsAuthIDJuly0702"
SLMS_EXCEPTION_RETRY_LIMIT: 4
SLMS_EXCEPTION_RETRY_DELAY: 50
SLMS_CONNECTION_TIMEOUT: 10000
SLMS_READ_TIMEOUT: 1000
SLMS_MIN_READ_TIMEOUT: 30000
SLMS_MAX_READ_TIMEOUT: 180000
SLMS_REQUEST_METHOD: "POST"
SLMS_AUTHENTICATION_METHOD: "Basic"
SLMS_CONTENT_TYPE: "application/vnd.slms.v1.0.0+json;charset=UTF-8"
SLMS_MAC_VAULT_ALIAS: "BA0141-PriMktgLoan-DEV_slsdauth2_AD_FHLMC"
SLMS_MAC_VAULT_TYPE: "Default"
SLMS_LOG_REQUEST_FLAG: true
SLMS_LOG_RESPONSE_FLAG: true
SLMS_SPLUNK_LOGGING_ENABLED_FLAG: true